[build]
  base = "/"
  command = "gatsby build"
  publish = "public"

[[redirects]]
  from = "https://rsapkf.netlify.app/*"
  to = "https://rsapkf.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/weblog/:splat"
  status = 301
  force = true
